# fly.toml app configuration file generated for quark-shift on 2025-07-24T20:49:51-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'quark-shift'
primary_region = 'gru'

[build.args]
  VITE_API_URL = "https://quark-shift-api.fly.dev"

[http_service]
  internal_port = 80
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'
